FROM python:3.9-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir fastapi uvicorn kafka-python
COPY app.py .
COPY static/ ./static/
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]